name: ESP32-S3 Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: ESP-IDF build and merge
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.2
          target: esp32s3
          path: '.'
          command: |
            idf.py build
            cd build
            esptool --chip esp32s3 merge-bin \
              -o esp32s3-n16r8-merged.bin \
              @flash_args

      - name: Prepare firmware
        run: |
          mkdir -p firmware/first-flash
          mkdir -p firmware/ota

          cp build/esp32s3-n16r8-merged.bin \
             firmware/first-flash/

          cp build/esp32-ota.bin \
             firmware/ota/

          echo "Firmware:"
          find firmware -type f -exec ls -lh {} \;

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-n16r8-firmware
          path: firmware/
